CREATE DATABASE IGLESIA;
USE IGLESIA;

CREATE TABLE CULTO(
	ID INT AUTO_INCREMENT,
    PRIMARY KEY(ID),
    SEDE VARCHAR(40) NOT NULL,
	INICIO DATETIME NOT NULL,
    FIN DATETIME NOT NULL,
    CUPOS INT NOT NULL
);
CREATE TABLE USUARIO(
	ID INT,
    PRIMARY KEY(ID),
    SEDE VARCHAR(40),
    NOMBRE VARCHAR(50) NOT NULL,
	TELEFONO INT,
    ROL VARCHAR(20),
    CONTRASENA VARCHAR(25)
);
CREATE TABLE CULTO_USUARIO(
	ID INT AUTO_INCREMENT,
    PRIMARY KEY(ID),
    IDCULTOFK INT NOT NULL,
    FOREIGN KEY(IDCULTOFK) REFERENCES CULTO(ID),
    IDUSUARIOFK INT NOT NULL,
    FOREIGN KEY(IDUSUARIOFK) REFERENCES USUARIO(ID)
);

INSERT INTO CULTO (`ID`,`SEDE`,`INICIO`,`FIN`,`CUPOS`) VALUES (1,'BRITALIA','2020-09-27 08:00:00','2020-09-27 09:00:00',2);
INSERT INTO CULTO (`ID`,`SEDE`,`INICIO`,`FIN`,`CUPOS`) VALUES (2,'BRITALIA','2020-09-27 10:00:00','2020-09-27 11:00:00',123);
INSERT INTO CULTO (`ID`,`SEDE`,`INICIO`,`FIN`,`CUPOS`) VALUES (3,'BRITALIA','2020-09-27 12:00:00','2020-09-27 13:00:00',1);
INSERT INTO CULTO (`ID`,`SEDE`,`INICIO`,`FIN`,`CUPOS`) VALUES (4,'BRITALIA','2020-09-27 17:00:00','2020-09-27 18:00:00',2);

CREATE VIEW CULTOS_CUPOS AS
SELECT ID,SEDE,HOUR(INICIO) AS HORA_INICIO, HOUR(FIN) AS HORA_FIN, CUPOS from CULTO;
SELECT * FROM CULTOS_CUPOS;

DELIMITER //
CREATE PROCEDURE RESTAR_CUPOS(IN CUPOS_RESERVADOS INT,IN ID_CULTO INT, IN SEDE_IGLESIA VARCHAR(40))
BEGIN
	UPDATE CULTO SET CUPOS = CUPOS - CUPOS_RESERVADOS WHERE ID = ID_CULTO AND SEDE = SEDE_IGLESIA;
END //
DELIMITER ;

SELECT * FROM CULTOS_CUPOS;
SELECT * FROM CULTOS_CUPOS WHERE SEDE = 'BRITALIA';
SELECT CUPOS FROM CULTOS_CUPOS WHERE ID = 3;
SELECT * FROM USUARIO;
SELECT * FROM CULTO;
SELECT * FROM CULTO_USUARIO;

CALL RESTAR_CUPOS(100,2,'BRITALIA');